// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3pyJ3R_IoksxOM-328AHLCaDpr5Na_7g',
    appId: '1:823649443605:web:4f7148ae77bb4cbf70531c',
    messagingSenderId: '823649443605',
    projectId: 'barber-shop-67293',
    authDomain: 'barber-shop-67293.firebaseapp.com',
    storageBucket: 'barber-shop-67293.appspot.com',
    measurementId: 'G-4349PK2SZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr7sHb0zx-l1a0OR2t4mGc0b7Xz_YRbwA',
    appId: '1:823649443605:android:f8295e6e6479edd270531c',
    messagingSenderId: '823649443605',
    projectId: 'barber-shop-67293',
    storageBucket: 'barber-shop-67293.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8z4BGd6jpashAaB38vrSZd41rlx52jMk',
    appId: '1:823649443605:ios:bdf690f18c0a1ec170531c',
    messagingSenderId: '823649443605',
    projectId: 'barber-shop-67293',
    storageBucket: 'barber-shop-67293.appspot.com',
    iosClientId: '823649443605-q37gsogi45n4ocqsqptpfstudi5lg079.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8z4BGd6jpashAaB38vrSZd41rlx52jMk',
    appId: '1:823649443605:ios:bdf690f18c0a1ec170531c',
    messagingSenderId: '823649443605',
    projectId: 'barber-shop-67293',
    storageBucket: 'barber-shop-67293.appspot.com',
    iosClientId: '823649443605-q37gsogi45n4ocqsqptpfstudi5lg079.apps.googleusercontent.com',
    iosBundleId: 'com.example.barberShop',
  );
}
